name: GitHub Actions Kafka Single Broker
on: [push]
jobs:
  Kafka-Single-Broker:
    runs-on: ubuntu-latest
    steps:          
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."             
      - name: List containers
        run: docker ps -a
      - name: Docker compose up
        run: docker compose up -d
      - name: Check if containers are up
        run: docker ps
      - name: Create a topic 
        run: docker compose exec broker kafka-topics --bootstrap-server localhost:9092 --topic events --create --partitions 1 --replication-factor 1
      - name: List topics
        run: docker compose exec broker kafka-topics --bootstrap-server localhost:9092 --list
      - name: Describe the topic
        run: docker compose exec broker kafka-topics --bootstrap-server localhost:9092 --describe --topic events
      - name: Check go version
        run: go version      
      - name: Run test
        run: go test . -v      
      - run: echo "🍏 This job's status is ${{ job.status }}."
